name = "miniwash-app"
main = "worker.js"
compatibility_date = "2024-02-10"

# ğŸŒ AQUÃ PONES TU DOMINIO
[env.production]
routes = [
  { pattern = "tudominio.com/*", zone_name = "tudominio.com" },
  { pattern = "www.tudominio.com/*", zone_name = "tudominio.com" }
]


