name = "miniwash-app"
main = "worker.js"
compatibility_date = "2024-02-10"

# ğŸŒ TU NUEVO DOMINIO GRATUITO
[env.production]
routes = [
  { pattern = "miniwash.eu.org/*", zone_name = "miniwash.eu.org" }
]
